name: release and push to central
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Docker Hub
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=latest -DgenerateBackupPoms=false
      - name: build artifact
        run: mvn clean install -DskipTests
      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/external-access-service/target/*.jar
          retention-days: 1
      - name: Docker build
        run: |
          docker build . -t epos/external-access-service:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: |
          docker push epos/external-access-service:latest